default_language_version:
  python: python3.12

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: poetry.lock
    -   id: check-yaml
    -   id: mixed-line-ending
        args: [ "--fix=lf" ]

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic,
                                  types-python-dateutil,
                                  types-PyYAML,
                                  pydantic-settings,
                                  fastapi,
                                  pytest,
                                  types-python-jose,
        ]
        args: [--strict]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.0
    hooks:
      # Run the linter.
      - id: ruff

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.8  # Use the latest stable version
    hooks:
    -   id: bandit
        args: ["-rq", "-c", "pyproject.toml", "-f", "yaml", "-o", ".reports/bandit-report.yaml"]
